### PR TITLE
Update fansi to 0.4.0

### PR DESCRIPTION
**Pull request by lolgab**
The fansi dependency is not shaded so this is a small binary incompatible change. Without updating scalafmt-core has a binary compatiblity issue since it depends on sourcecode `0.3.0` through scalameta `trees` and on sourcecode `0.2.7` through fansi `0.3.0`. Updating fansi fixes this incompatibility.

### CODE REVIEW

**Comment by tgodzik** [comment]
Looks like we should also bump Scala JS, we haven't kept the repo up to date much :thinking:

**Comment by lolgab** [comment]
@tgodzik can you approve the pipeline again?

**Comment by tgodzik** [comment]
> @tgodzik can you approve the pipeline again?

Done! Though it seems now to be failing on native :/  Most likely a bump is needed there too

**Comment by lolgab** [comment]
It's finally green! Thanks for the patience to approve all the workflows 😄.
(Github should change how this works IMO, I've contributed many merged PRs to scalameta and I still need approve on every commit to run the CI)

**Pull request merged**
