### PR TITLE
Support Scala Native + Scala 3

### LINKED ISSUE #179: Support Scala 3 Native
Hi,
From my [checking](https://mvnrepository.com/artifact/com.geirsson/metaconfig-core), this project doesn't support Scala 3 Native.
Can this library add Scala 3 Native support?
Thanks.

### PR DESCRIPTION
**Pull request by lolgab**
Fixes #179

Fix most warnings
Update Scala 3 to 3.3.1
Update paiges-core to 0.4.3
Update Scala.js to 1.13.2
Update sbt-mdoc to 2.3.7
Update scala-collection-compat to 2.11.0
Update munit to 10.0.0-M10
Remove munit-scalacheck from main dependencies
Add only scalacheck as a dependency
Update Scala Native to 0.4.15
Add Scala 3 to all projects
Move `java.io.File` specific test to `jvm-native` folder

### CODE REVIEW

**Comment by lolgab** [comment]
@tgodzik The CI is finally green :) Can I ask you a review?

**Review by tgodzik — APPROVED** [review]
Looks good! Thanks for looking into this, I haven't had much time to look at metaconfig over the past year.

Should we do a release or do you want to test it out still?

**Comment by tgodzik** [comment]
Looks like the release is failing though https://github.com/scalameta/metaconfig/actions/runs/6364431764/job/17280704001 <- anything looks familiar?

**Comment by lolgab** [comment]
I'll give it a look tomorrow :+1:

**Comment by lolgab** [comment]
Opened #187 which should fix the problem on publishing

**Pull request merged**
