### PR TITLE
Update versions to support Scala Native

### PR DESCRIPTION
**Pull request by ekrich**

### CODE REVIEW

**Review by olafurpg — APPROVED** [review]
LGTM 👍 thank you!

**Comment by ekrich** [comment]
Thanks @olafurpg, we are waiting on the Scala Native support for paiges https://github.com/typelevel/paiges/pull/338.

Once everything is working in CI then we should be good to go.

**Comment by larsrh** [comment]
Paiges 0.4.1 is out

**Comment by tgodzik** [comment]
@ekrich should I take a look at the PR and update paiges?

**Comment by ekrich** [comment]
I was working on update `upickle` so I could use the latest that has all the cross projects. 

I did see that paiges was updated.

**Comment by ekrich** [comment]
@tgodzik Between `ujson` 0.9.3 and 0.9.4, `SyncParser` was dropped with no suggestions.
https://www.javadoc.io/doc/com.lihaoyi/ujson_2.12/0.9.3/index.html
Any Ideas?
https://github.com/scalameta/metaconfig/blob/master/metaconfig-json/src/main/scala/metaconfig/internal/JsonConfParser.scala

**Comment by tgodzik** [comment]
@ekrich what do you think about https://github.com/scalameta/metaconfig/pull/105 ?

**Comment by tgodzik** [comment]
@ekrich the other PR is merged and CI is fixed. We should be good to rebase this one :tada:

**Comment by ekrich** [comment]
Sure, I will go ahead and rebase and then make the other changes. Note that @olafurpg said it was ok to drop 2.11 because paiges is 2.12+.

**Comment by ekrich** [comment]
This works without tests but I cannot add them until the following project gets Native support.
https://github.com/alexarchambault/scalacheck-shapeless

I can do this but it will take a few days - hopefully. Added ticket: https://github.com/alexarchambault/scalacheck-shapeless/issues/205

**Comment by tgodzik** [comment]
It's only `CodecRoundtripSuite` test from what I see, could we add is into a separate `jvm` folder? We wouldn't compile or run it for native.

**Comment by ekrich** [comment]
I guess it is pretty much up to you. The tests being cross project would be nice. We could add a ticket to the scalacheck-shapeless and do that longer term on another PR - I don't know how much it is used so I don't know if it could be removed.

**Review by tgodzik — APPROVED** [review]
I can follow up with a PR to separate the test tomorrow. I think we should be ok to merge and release? What do you think @olafurpg ? I fixed the release and it should work alright.

**Comment by olafurpg** [comment]
LGTM ship it!

**Pull request merged**
