### PR TITLE
support scala-js 1.x. drop Scala 2.11.x

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Comment by SethTisue** [comment]
#139 overlaps with this

**Review by olafurpg — COMMENTED** [review]
Thank you for this contribution! Can you elaborate on the motivation for this change? Scalafix depends on Metaconfig and still supports 2.11.  cc/ @mlachkar

I personally don’t mind dropping 2.11 support.

**Comment by mlachkar** [comment]
I though the support for 2.11 was drop since 0.9.10
https://index.scala-lang.org/artifacts/olafurpg/metaconfig
In scalafix we froze the version of metaconfig for 2.11.

**Comment by olafurpg** [comment]
Thanks! Looks good to me, happy to merge once the git conflict is resolved and CI is green 👍

**Pull request closed without merging**
